
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"       # RabbitMQ server port
      - "15672:15672"     # RabbitMQ management UI port
    networks:
      - rabbitmq_net
    restart: always

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net
    command: ["npm", "start"]
    restart: always

  scanner:
    build: ./scanner
    container_name: scanner
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net
    restart: always

networks:
  rabbitmq_net:
    driver: bridge
